-- NEIS Circle v11 — account lifecycle, platform access controls and community safety.
-- Idempotent; preserves every existing account and content row.
begin;

alter table public.profiles add column if not exists account_status text not null default 'active';
alter table public.profiles add column if not exists deactivated_at timestamptz;
alter table public.profiles add column if not exists accepted_guidelines_at timestamptz;
alter table public.profiles add column if not exists accepted_guidelines_version text;

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_account_status_check' and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles add constraint profiles_account_status_check
      check (account_status in ('active','deactivated','blocked'));
  end if;
end $$;

create table if not exists public.admin_allowlist (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.blocked_accounts (
  id bigint generated by default as identity primary key,
  email text,
  user_id uuid references auth.users(id) on delete cascade,
  reason text not null default 'Access disabled by an administrator',
  blocked_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint blocked_accounts_target_check check (email is not null or user_id is not null)
);

create unique index if not exists blocked_accounts_email_unique
  on public.blocked_accounts (lower(email)) where email is not null;
create unique index if not exists blocked_accounts_user_unique
  on public.blocked_accounts (user_id) where user_id is not null;

create table if not exists public.moderation_terms (
  id bigint generated by default as identity primary key,
  term text not null,
  language text not null default 'any',
  category text not null default 'hostile',
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists moderation_terms_unique on public.moderation_terms(lower(term));

insert into public.admin_allowlist(email) values ('aboda.ahmed122010@gmail.com')
on conflict do nothing;

insert into public.moderation_terms(term,language,category) values
  ('fuck','en','explicit'),('bitch','en','hostile'),('porn','en','explicit'),
  ('nude','en','explicit'),('kill yourself','en','threat'),
  ('كس امك','ar','hostile'),('ابن المتناكة','ar','hostile'),('شرموط','ar','explicit'),
  ('نيك','ar','explicit'),('اقتل نفسك','ar','threat')
on conflict do nothing;

create or replace function public.current_user_email()
returns text language sql stable security definer set search_path=public,auth as $$
  select lower(email) from auth.users where id=auth.uid();
$$;

create or replace function public.account_is_allowed(member uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public,auth as $$
  select member is not null
    and coalesce((select account_status='active' from public.profiles where id=member),true)
    and not exists (
      select 1 from public.blocked_accounts b
      left join auth.users u on u.id=member
      where b.user_id=member or (b.email is not null and lower(b.email)=lower(u.email))
    );
$$;

create or replace function public.account_access_status()
returns jsonb language sql stable security definer set search_path=public,auth as $$
  select jsonb_build_object(
    'status', case
      when exists (
        select 1 from public.blocked_accounts b
        left join auth.users u on u.id=auth.uid()
        where b.user_id=auth.uid() or (b.email is not null and lower(b.email)=lower(u.email))
      ) then 'blocked'
      else coalesce((select account_status from public.profiles where id=auth.uid()),'active')
    end,
    'reason', coalesce((
      select b.reason from public.blocked_accounts b
      left join auth.users u on u.id=auth.uid()
      where b.user_id=auth.uid() or (b.email is not null and lower(b.email)=lower(u.email))
      order by b.created_at desc limit 1
    ),''),
    'guidelines_version', coalesce((select accepted_guidelines_version from public.profiles where id=auth.uid()),'')
  );
$$;

create or replace function public.accept_guidelines(version text default '2026.1')
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  update public.profiles set accepted_guidelines_at=now(), accepted_guidelines_version=version where id=auth.uid();
  return found;
end;
$$;

create or replace function public.deactivate_my_account()
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  update public.profiles set account_status='deactivated',deactivated_at=now() where id=auth.uid();
  return found;
end;
$$;

create or replace function public.reactivate_my_account()
returns boolean language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if exists (
    select 1 from public.blocked_accounts b left join auth.users u on u.id=auth.uid()
    where b.user_id=auth.uid() or (b.email is not null and lower(b.email)=lower(u.email))
  ) then raise exception 'account_blocked'; end if;
  update public.profiles set account_status='active',deactivated_at=null where id=auth.uid();
  return found;
end;
$$;

create or replace function public.delete_my_account()
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare deleted_count bigint;
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  delete from auth.users where id=auth.uid();
  get diagnostics deleted_count = row_count;
  return deleted_count > 0;
end;
$$;

create or replace function public.admin_set_account_block(
  target_email text default null,
  target_user uuid default null,
  should_block boolean default true,
  block_reason text default 'Access disabled by an administrator'
)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare resolved_user uuid; resolved_email text;
begin
  if not public.is_admin() then raise exception 'administrator_required'; end if;
  resolved_email := nullif(lower(trim(target_email)), '');
  resolved_user := target_user;
  if resolved_user is null and resolved_email is not null then
    select id into resolved_user from auth.users where lower(email)=resolved_email limit 1;
  end if;
  if resolved_email is null and resolved_user is not null then
    select lower(email) into resolved_email from auth.users where id=resolved_user;
  end if;
  if resolved_user=auth.uid() then raise exception 'cannot_block_yourself'; end if;
  if resolved_email is null and resolved_user is null then raise exception 'account_not_found'; end if;
  if should_block then
    delete from public.blocked_accounts
      where (resolved_user is not null and user_id=resolved_user)
         or (resolved_email is not null and lower(email)=resolved_email);
    insert into public.blocked_accounts(email,user_id,reason,blocked_by)
    values(resolved_email,resolved_user,coalesce(nullif(trim(block_reason),''),'Access disabled by an administrator'),auth.uid());
    if resolved_user is not null then update public.profiles set account_status='blocked' where id=resolved_user; end if;
  else
    delete from public.blocked_accounts
      where (resolved_user is not null and user_id=resolved_user)
         or (resolved_email is not null and lower(email)=resolved_email);
    if resolved_user is not null then update public.profiles set account_status='active',deactivated_at=null where id=resolved_user; end if;
  end if;
  return true;
end;
$$;

create or replace function public.apply_admin_allowlist()
returns trigger language plpgsql security definer set search_path=public,auth as $$
begin
  if exists (
    select 1 from auth.users u join public.admin_allowlist a on lower(a.email)=lower(u.email)
    where u.id=new.id
  ) then new.role='admin'; end if;
  return new;
end;
$$;
drop trigger if exists apply_admin_allowlist_on_profile on public.profiles;
create trigger apply_admin_allowlist_on_profile before insert on public.profiles
for each row execute function public.apply_admin_allowlist();

update public.profiles p set role='admin'
from auth.users u join public.admin_allowlist a on lower(a.email)=lower(u.email)
where p.id=u.id;

create or replace function public.enforce_community_safety()
returns trigger language plpgsql security definer set search_path=public as $$
declare content text; bad public.moderation_terms%rowtype;
begin
  if not public.account_is_allowed(auth.uid()) then raise exception 'account_access_disabled'; end if;
  content := lower(concat_ws(' ',
    to_jsonb(new)->>'title',to_jsonb(new)->>'body',to_jsonb(new)->>'name',
    to_jsonb(new)->>'description',to_jsonb(new)->>'caption_en',to_jsonb(new)->>'caption_ar',
    to_jsonb(new)->>'title_en',to_jsonb(new)->>'title_ar',to_jsonb(new)->>'excerpt_en',
    to_jsonb(new)->>'excerpt_ar',to_jsonb(new)->>'content_en',to_jsonb(new)->>'content_ar',
    to_jsonb(new)->>'bio',to_jsonb(new)->>'full_name'
  ));
  select * into bad from public.moderation_terms m
  where m.active and length(trim(m.term))>1 and position(lower(m.term) in content)>0 limit 1;
  if found then raise exception 'community_content_rejected:%',bad.category; end if;
  return new;
end;
$$;

do $$ declare tab text; begin
  foreach tab in array array['posts','comments','messages','circle_messages','articles','gallery_items','circles'] loop
    if to_regclass('public.'||tab) is not null then
      execute format('drop trigger if exists enforce_community_safety_trigger on public.%I',tab);
      execute format('create trigger enforce_community_safety_trigger before insert or update on public.%I for each row execute function public.enforce_community_safety()',tab);
    end if;
  end loop;
end $$;

alter table public.blocked_accounts enable row level security;
alter table public.moderation_terms enable row level security;
alter table public.admin_allowlist enable row level security;

drop policy if exists blocked_accounts_admin_read on public.blocked_accounts;
create policy blocked_accounts_admin_read on public.blocked_accounts for select to authenticated using (public.is_admin());
drop policy if exists moderation_terms_members_read on public.moderation_terms;
create policy moderation_terms_members_read on public.moderation_terms for select to authenticated using (true);
drop policy if exists moderation_terms_admin_manage on public.moderation_terms;
create policy moderation_terms_admin_manage on public.moderation_terms for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists admin_allowlist_admin_read on public.admin_allowlist;
create policy admin_allowlist_admin_read on public.admin_allowlist for select to authenticated using (public.is_admin());

grant select on public.blocked_accounts,public.moderation_terms to authenticated;
grant insert,update,delete on public.moderation_terms to authenticated;
grant execute on function public.account_access_status(),public.accept_guidelines(text),
  public.deactivate_my_account(),public.reactivate_my_account(),public.delete_my_account(),
  public.admin_set_account_block(text,uuid,boolean,text) to authenticated;

commit;
select 'NEIS Circle v11 account safety migration complete' as result;
