-- NEIS Circle v28 — persistent article likes and share events.
begin;

create table if not exists public.article_reactions (
  article_id bigint not null references public.articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id,user_id)
);

create index if not exists article_reactions_user_idx
  on public.article_reactions(user_id,created_at desc);

alter table public.article_reactions enable row level security;

drop policy if exists article_reactions_read on public.article_reactions;
create policy article_reactions_read on public.article_reactions
for select to authenticated using (
  exists (
    select 1 from public.articles a
    where a.id=article_reactions.article_id
      and (a.status='published' or a.author_id=auth.uid() or public.is_admin())
  )
);

drop policy if exists article_reactions_create on public.article_reactions;
create policy article_reactions_create on public.article_reactions
for insert to authenticated with check (
  user_id=auth.uid()
  and exists (
    select 1 from public.articles a
    where a.id=article_reactions.article_id and a.status='published'
  )
);

drop policy if exists article_reactions_delete_owner on public.article_reactions;
create policy article_reactions_delete_owner on public.article_reactions
for delete to authenticated using (user_id=auth.uid() or public.is_admin());

grant select,insert,delete on public.article_reactions to authenticated;

create table if not exists public.article_shares (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  method text not null default 'copy' check (method in ('native','copy')),
  created_at timestamptz not null default now()
);

create index if not exists article_shares_article_created_idx
  on public.article_shares(article_id,created_at desc);
create index if not exists article_shares_user_idx
  on public.article_shares(user_id,created_at desc);

alter table public.article_shares enable row level security;

drop policy if exists article_shares_read on public.article_shares;
create policy article_shares_read on public.article_shares
for select to authenticated using (
  exists (
    select 1 from public.articles a
    where a.id=article_shares.article_id
      and (a.status='published' or a.author_id=auth.uid() or public.is_admin())
  )
);

drop policy if exists article_shares_create on public.article_shares;
create policy article_shares_create on public.article_shares
for insert to authenticated with check (
  user_id=auth.uid()
  and exists (
    select 1 from public.articles a
    where a.id=article_shares.article_id and a.status='published'
  )
);

grant select,insert on public.article_shares to authenticated;
grant usage,select on sequence public.article_shares_id_seq to authenticated;

create or replace function public.notify_article_like()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  article_owner uuid;
  article_title text;
  liker_name text;
begin
  select a.author_id,coalesce(nullif(a.title_en,''),nullif(a.title_ar,''),'Article')
    into article_owner,article_title
  from public.articles a where a.id=new.article_id and a.status='published';

  if article_owner is null or article_owner=new.user_id then return new; end if;
  select coalesce(nullif(p.full_name,''),'A student') into liker_name
  from public.profiles p where p.id=new.user_id;

  insert into public.notifications(user_id,type,title,body,route)
  values (
    article_owner,
    'reaction',
    'New like on your article',
    coalesce(liker_name,'A student')||' liked “'||article_title||'”.',
    'articles/'||new.article_id::text
  );
  return new;
end;
$$;

drop trigger if exists article_reactions_notify on public.article_reactions;
create trigger article_reactions_notify after insert on public.article_reactions
for each row execute function public.notify_article_like();

do $$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists(
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename='article_reactions'
    ) then alter publication supabase_realtime add table public.article_reactions; end if;
    if not exists(
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename='article_shares'
    ) then alter publication supabase_realtime add table public.article_shares; end if;
  end if;
end;
$$;

commit;
select 'NEIS Circle v28 article direction and engagement backend ready' as result;
