-- NEIS Circle v14 — private verified identities, dual-identity bans and admin-only report identity details.
-- Data-preserving and safe to apply before the WhatsApp provider is activated.
begin;
alter table public.reports alter column target_id type text using target_id::text;

create table if not exists public.private_user_identities (
  user_id uuid primary key references auth.users(id) on delete cascade,
  normalized_email text not null,
  email_verified_at timestamptz,
  phone_e164 text,
  phone_verified_at timestamptz,
  verification_required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint private_identity_phone_format check (phone_e164 is null or phone_e164 ~ '^\+[1-9][0-9]{7,14}$')
);
create unique index if not exists private_identity_email_unique on public.private_user_identities(lower(normalized_email));
create unique index if not exists private_identity_phone_unique on public.private_user_identities(phone_e164) where phone_e164 is not null;

-- Existing production users remain usable. The verification gate applies only to accounts created after activation.
insert into public.private_user_identities(user_id,normalized_email,email_verified_at,phone_e164,phone_verified_at,verification_required)
select id,lower(email),email_confirmed_at,
       case when phone ~ '^\+[1-9][0-9]{7,14}$' then phone else null end,
       case when phone ~ '^\+[1-9][0-9]{7,14}$' then phone_confirmed_at else null end,
       false
from auth.users
where email is not null
on conflict (user_id) do update set
  normalized_email=excluded.normalized_email,
  email_verified_at=coalesce(excluded.email_verified_at,public.private_user_identities.email_verified_at),
  updated_at=now();

create table if not exists public.platform_security_settings (
  singleton boolean primary key default true check (singleton),
  whatsapp_signup_required boolean not null default false,
  activated_at timestamptz,
  activated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.platform_security_settings(singleton) values(true) on conflict do nothing;

create table if not exists public.otp_rate_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  phone_e164 text not null check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  action text not null check (action in ('send','verify')),
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists otp_rate_user_created_idx on public.otp_rate_events(user_id,action,created_at desc);
create index if not exists otp_rate_phone_created_idx on public.otp_rate_events(phone_e164,action,created_at desc);

alter table public.blocked_accounts add column if not exists phone_e164 text;
do $$ begin
  alter table public.blocked_accounts drop constraint if exists blocked_accounts_target_check;
  alter table public.blocked_accounts add constraint blocked_accounts_target_check
    check (email is not null or user_id is not null or phone_e164 is not null);
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.blocked_accounts add constraint blocked_accounts_phone_format
    check (phone_e164 is null or phone_e164 ~ '^\+[1-9][0-9]{7,14}$');
exception when duplicate_object then null; end $$;
create unique index if not exists blocked_accounts_phone_unique on public.blocked_accounts(phone_e164) where phone_e164 is not null;

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete restrict,
  action text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  target_type text,
  target_id text,
  reason text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists moderation_actions_admin_created_idx on public.moderation_actions(admin_id,created_at desc);
create index if not exists moderation_actions_target_created_idx on public.moderation_actions(target_user_id,created_at desc);

create or replace function public.sync_private_identity()
returns trigger language plpgsql security definer set search_path=public,auth as $$
begin
  if new.email is null then return new; end if;
  insert into public.private_user_identities(
    user_id,normalized_email,email_verified_at,phone_e164,phone_verified_at,verification_required,updated_at
  ) values (
    new.id,lower(new.email),new.email_confirmed_at,
    case when new.phone ~ '^\+[1-9][0-9]{7,14}$' then new.phone else null end,
    case when new.phone ~ '^\+[1-9][0-9]{7,14}$' then new.phone_confirmed_at else null end,
    true,now()
  ) on conflict (user_id) do update set
    normalized_email=excluded.normalized_email,
    email_verified_at=coalesce(excluded.email_verified_at,public.private_user_identities.email_verified_at),
    phone_e164=coalesce(public.private_user_identities.phone_e164,excluded.phone_e164),
    phone_verified_at=coalesce(public.private_user_identities.phone_verified_at,excluded.phone_verified_at),
    updated_at=now();
  return new;
end;
$$;
drop trigger if exists sync_private_identity_trigger on auth.users;
create trigger sync_private_identity_trigger after insert or update of email,email_confirmed_at,phone,phone_confirmed_at on auth.users
for each row execute function public.sync_private_identity();

create or replace function public.identity_verification_status()
returns jsonb language sql stable security definer set search_path=public,auth as $$
  select jsonb_build_object(
    'verification_required',coalesce(s.whatsapp_signup_required,false) and coalesce(i.verification_required,true),
    'email_verified',i.email_verified_at is not null,
    'phone_verified',i.phone_verified_at is not null,
    'phone_masked',case when i.phone_e164 is null then '' else left(i.phone_e164,3)||repeat('•',greatest(length(i.phone_e164)-7,2))||right(i.phone_e164,4) end,
    'verified_at',i.phone_verified_at
  )
  from public.private_user_identities i
  cross join public.platform_security_settings s
  where i.user_id=auth.uid() and s.singleton=true;
$$;

create or replace function public.account_is_allowed(member uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public,auth as $$
  select member is not null
    and coalesce((select account_status='active' from public.profiles where id=member),true)
    and not exists (
      select 1
      from public.blocked_accounts b
      left join auth.users u on u.id=member
      left join public.private_user_identities i on i.user_id=member
      where b.user_id=member
         or (b.email is not null and lower(b.email)=lower(u.email))
         or (b.phone_e164 is not null and b.phone_e164=i.phone_e164)
    );
$$;

create or replace function public.account_access_status()
returns jsonb language sql stable security definer set search_path=public,auth as $$
  select jsonb_build_object(
    'status',case when exists(
      select 1 from public.blocked_accounts b
      left join auth.users u on u.id=auth.uid()
      left join public.private_user_identities i on i.user_id=auth.uid()
      where b.user_id=auth.uid()
         or (b.email is not null and lower(b.email)=lower(u.email))
         or (b.phone_e164 is not null and b.phone_e164=i.phone_e164)
    ) then 'blocked' else coalesce((select account_status from public.profiles where id=auth.uid()),'active') end,
    'reason',coalesce((select b.reason from public.blocked_accounts b
      left join auth.users u on u.id=auth.uid()
      left join public.private_user_identities i on i.user_id=auth.uid()
      where b.user_id=auth.uid()
         or (b.email is not null and lower(b.email)=lower(u.email))
         or (b.phone_e164 is not null and b.phone_e164=i.phone_e164)
      order by b.created_at desc limit 1),''),
    'guidelines_version',coalesce((select accepted_guidelines_version from public.profiles where id=auth.uid()),'')
  );
$$;

create or replace function public.admin_set_account_block(
  target_email text default null,
  target_user uuid default null,
  should_block boolean default true,
  block_reason text default 'Access disabled by an administrator'
)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare resolved_user uuid; resolved_email text; resolved_phone text; reason_value text;
begin
  if not public.is_admin() then raise exception 'administrator_required'; end if;
  resolved_email:=nullif(lower(trim(target_email)),'');
  resolved_user:=target_user;
  if resolved_user is null and resolved_email is not null then
    select id into resolved_user from auth.users where lower(email)=resolved_email limit 1;
  end if;
  if resolved_user is not null then
    select lower(u.email),i.phone_e164 into resolved_email,resolved_phone
    from auth.users u left join public.private_user_identities i on i.user_id=u.id where u.id=resolved_user;
  end if;
  if resolved_user=auth.uid() then raise exception 'cannot_block_yourself'; end if;
  if resolved_email is null and resolved_user is null and resolved_phone is null then raise exception 'account_not_found'; end if;
  reason_value:=coalesce(nullif(trim(block_reason),''),'Access disabled by an administrator');
  if should_block then
    delete from public.blocked_accounts where
      (resolved_user is not null and user_id=resolved_user) or
      (resolved_email is not null and lower(email)=resolved_email) or
      (resolved_phone is not null and phone_e164=resolved_phone);
    insert into public.blocked_accounts(email,user_id,phone_e164,reason,blocked_by)
    values(resolved_email,resolved_user,resolved_phone,reason_value,auth.uid());
    if resolved_user is not null then update public.profiles set account_status='blocked' where id=resolved_user; end if;
    insert into public.moderation_actions(admin_id,action,target_user_id,target_type,target_id,reason,metadata)
    values(auth.uid(),'block_identity',resolved_user,'account',coalesce(resolved_user::text,resolved_email,resolved_phone),reason_value,
      jsonb_build_object('email',resolved_email,'phone',resolved_phone));
  else
    delete from public.blocked_accounts where
      (resolved_user is not null and user_id=resolved_user) or
      (resolved_email is not null and lower(email)=resolved_email) or
      (resolved_phone is not null and phone_e164=resolved_phone);
    if resolved_user is not null then update public.profiles set account_status='active',deactivated_at=null where id=resolved_user; end if;
    insert into public.moderation_actions(admin_id,action,target_user_id,target_type,target_id,reason)
    values(auth.uid(),'unblock_identity',resolved_user,'account',coalesce(resolved_user::text,resolved_email,resolved_phone),'');
  end if;
  return true;
end;
$$;

create or replace function public.try_uuid(value text)
returns uuid language plpgsql immutable as $$ begin return value::uuid; exception when others then return null; end $$;
create or replace function public.try_bigint(value text)
returns bigint language plpgsql immutable as $$ begin return value::bigint; exception when others then return null; end $$;

create or replace function public.admin_report_details()
returns table(
  id uuid,status text,target_type text,target_id text,reason text,details text,created_at timestamptz,
  reported_content text,reported_user_id uuid,reported_display_name text,reported_username text,
  reported_email text,reported_phone text,reporter_id uuid,reporter_display_name text,reporter_username text
) language sql stable security definer set search_path=public,auth as $$
  select r.id,r.status,r.target_type,r.target_id,r.reason,r.details,r.created_at,
    coalesce(
      case when r.target_type='profile' then rp.full_name end,
      case when r.target_type='post' then (select left(concat_ws(' — ',p.title,p.body),1200) from public.posts p where p.id=public.try_uuid(r.target_id)) end,
      case when r.target_type='comment' then (select left(c.body,1200) from public.comments c where c.id=public.try_uuid(r.target_id)) end,
      case when r.target_type='circle' then (select left(concat_ws(' — ',c.name,c.description),1200) from public.circles c where c.id=public.try_uuid(r.target_id)) end,
      case when r.target_type='message' then (select left(m.body,1200) from public.messages m where m.id=public.try_uuid(r.target_id)) end,
      case when r.target_type='circle_message' then (select left(m.body,1200) from public.circle_messages m where m.id=public.try_bigint(r.target_id)) end,
      case when r.target_type='gallery' then (select left(concat_ws(' — ',g.caption_en,g.caption_ar),1200) from public.gallery_items g where g.id=public.try_bigint(r.target_id)) end,
      case when r.target_type='article' then (select left(concat_ws(' — ',a.title_en,a.title_ar,a.excerpt_en,a.excerpt_ar),1200) from public.articles a where a.id=public.try_bigint(r.target_id)) end,
      case when r.target_type='meeting' then (select left(concat_ws(' — ',m.title,m.description),1200) from public.circle_meetings m where m.id=public.try_uuid(r.target_id)) end,
      '[Content unavailable]'
    ) as reported_content,
    owner_data.owner_id,rp.full_name,rp.username,
    case when ri.email_verified_at is not null then ri.normalized_email else null end,
    case when ri.phone_verified_at is not null then ri.phone_e164 else null end,
    r.reporter_id,reporter.full_name,reporter.username
  from public.reports r
  cross join lateral (select coalesce(
    case when r.target_type='profile' then public.try_uuid(r.target_id) end,
    case when r.target_type='post' then (select p.author_id from public.posts p where p.id=public.try_uuid(r.target_id)) end,
    case when r.target_type='comment' then (select c.author_id from public.comments c where c.id=public.try_uuid(r.target_id)) end,
    case when r.target_type='circle' then (select c.owner_id from public.circles c where c.id=public.try_uuid(r.target_id)) end,
    case when r.target_type='message' then (select m.sender_id from public.messages m where m.id=public.try_uuid(r.target_id)) end,
    case when r.target_type='circle_message' then (select m.sender_id from public.circle_messages m where m.id=public.try_bigint(r.target_id)) end,
    case when r.target_type='gallery' then (select g.author_id from public.gallery_items g where g.id=public.try_bigint(r.target_id)) end,
    case when r.target_type='article' then (select a.author_id from public.articles a where a.id=public.try_bigint(r.target_id)) end,
    case when r.target_type='meeting' then (select m.creator_id from public.circle_meetings m where m.id=public.try_uuid(r.target_id)) end
  ) as owner_id) owner_data
  left join public.profiles rp on rp.id=owner_data.owner_id
  left join public.private_user_identities ri on ri.user_id=owner_data.owner_id
  left join public.profiles reporter on reporter.id=r.reporter_id
  where public.is_admin()
  order by r.created_at desc;
$$;

create or replace function public.audit_report_status_change()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.status is distinct from old.status and public.is_admin() then
    insert into public.moderation_actions(admin_id,action,target_type,target_id,reason,metadata)
    values(auth.uid(),'report_status_changed',new.target_type,new.target_id,new.reason,jsonb_build_object('from',old.status,'to',new.status,'report_id',new.id));
  end if;
  return new;
end;
$$;
drop trigger if exists audit_report_status_change_trigger on public.reports;
create trigger audit_report_status_change_trigger after update of status on public.reports
for each row execute function public.audit_report_status_change();

-- Supabase Before User Created hook. It rejects blocked emails before an Auth account is created.
create or replace function public.reject_blocked_signup(input jsonb)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare candidate_email text:=lower(input->'user'->>'email');
begin
  if candidate_email is not null and exists(select 1 from public.blocked_accounts b where lower(b.email)=candidate_email) then
    return jsonb_build_object('error',jsonb_build_object('http_code',403,'message','This identity cannot register for NEIS Circle.'));
  end if;
  return '{}'::jsonb;
end;
$$;

alter table public.private_user_identities enable row level security;
alter table public.platform_security_settings enable row level security;
alter table public.otp_rate_events enable row level security;
alter table public.moderation_actions enable row level security;

drop policy if exists private_identities_admin_read on public.private_user_identities;
create policy private_identities_admin_read on public.private_user_identities for select to authenticated using (public.is_admin());
drop policy if exists security_settings_admin_read on public.platform_security_settings;
create policy security_settings_admin_read on public.platform_security_settings for select to authenticated using (public.is_admin());
drop policy if exists moderation_actions_admin_read on public.moderation_actions;
create policy moderation_actions_admin_read on public.moderation_actions for select to authenticated using (public.is_admin());

revoke all on public.private_user_identities,public.platform_security_settings,public.otp_rate_events,public.moderation_actions from anon;
grant select on public.private_user_identities,public.platform_security_settings,public.moderation_actions to authenticated;
grant execute on function public.identity_verification_status(),public.admin_report_details(),public.admin_set_account_block(text,uuid,boolean,text) to authenticated;
revoke execute on function public.reject_blocked_signup(jsonb) from anon,authenticated;
grant execute on function public.reject_blocked_signup(jsonb) to supabase_auth_admin;
grant usage on schema public to supabase_auth_admin;

commit;
select 'NEIS Circle v14 identity and moderation migration ready; WhatsApp gate remains off until provider activation.' as result;
