-- Main-admin-only, time-limited DM safety review requests with audit logging.
create table if not exists public.admin_dm_review_requests (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid null references public.profiles(id) on delete set null,
  conversation_id uuid null references public.conversations(id) on delete set null,
  reason text not null check (char_length(btrim(reason)) between 3 and 500),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  closed_at timestamptz null
);

create index if not exists admin_dm_review_requests_admin_created_idx
  on public.admin_dm_review_requests(admin_id, created_at desc);
create index if not exists admin_dm_review_requests_target_created_idx
  on public.admin_dm_review_requests(target_user_id, created_at desc);

alter table public.admin_dm_review_requests enable row level security;
revoke all on table public.admin_dm_review_requests from public, anon, authenticated;

create table if not exists public.admin_dm_audit_log (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.admin_dm_review_requests(id) on delete restrict,
  admin_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (action in ('request','view')),
  target_user_id uuid null,
  conversation_id uuid null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_dm_audit_log_request_created_idx
  on public.admin_dm_audit_log(request_id, created_at desc);

alter table public.admin_dm_audit_log enable row level security;
revoke all on table public.admin_dm_audit_log from public, anon, authenticated;

create or replace function public.admin_search_dm_users(search_input text)
returns table (user_id uuid, full_name text, username text, branch text, grade text)
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare normalized text := btrim(coalesce(search_input,''));
begin
  perform 1 from auth.users u join public.profiles p on p.id=u.id
  where u.id=auth.uid()
    and lower(coalesce(u.email,''))='mreyadishere@gmail.com'
    and p.role='admin'
    and coalesce(p.account_status,'active')='active';
  if not found then raise exception 'Not authorized' using errcode='42501'; end if;
  if char_length(normalized) < 2 then return; end if;

  return query
  select p.id,p.full_name,p.username,p.branch,p.grade
  from public.profiles p
  where coalesce(p.account_status,'active')='active'
    and (p.full_name ilike '%'||normalized||'%' or coalesce(p.username,'') ilike '%'||normalized||'%')
  order by case when lower(p.full_name)=lower(normalized) then 0 else 1 end,p.full_name
  limit 20;
end;
$$;

create or replace function public.admin_list_user_dm_conversations(user_id_input uuid)
returns table (
  conversation_id uuid, other_user_id uuid, other_name text, other_username text,
  updated_at timestamptz, message_count bigint, last_message_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
begin
  perform 1 from auth.users u join public.profiles p on p.id=u.id
  where u.id=auth.uid()
    and lower(coalesce(u.email,''))='mreyadishere@gmail.com'
    and p.role='admin'
    and coalesce(p.account_status,'active')='active';
  if not found then raise exception 'Not authorized' using errcode='42501'; end if;

  return query
  select c.id,om.user_id,op.full_name,op.username,c.updated_at,
    (select count(*) from public.messages m where m.conversation_id=c.id and m.deleted_at is null),
    (select max(m.created_at) from public.messages m where m.conversation_id=c.id)
  from public.conversations c
  join public.conversation_members tm on tm.conversation_id=c.id and tm.user_id=user_id_input
  left join public.conversation_members om on om.conversation_id=c.id and om.user_id<>user_id_input
  left join public.profiles op on op.id=om.user_id
  where c.kind='direct'
  order by coalesce((select max(m2.created_at) from public.messages m2 where m2.conversation_id=c.id),c.updated_at) desc
  limit 100;
end;
$$;

create or replace function public.admin_create_dm_review_request(
  conversation_id_input uuid,target_user_id_input uuid,reason_input text
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  request_id uuid;
  normalized_reason text := btrim(coalesce(reason_input,''));
begin
  perform 1 from auth.users u join public.profiles p on p.id=u.id
  where u.id=auth.uid()
    and lower(coalesce(u.email,''))='mreyadishere@gmail.com'
    and p.role='admin'
    and coalesce(p.account_status,'active')='active';
  if not found then raise exception 'Not authorized' using errcode='42501'; end if;
  if char_length(normalized_reason) < 3 then raise exception 'A review reason is required' using errcode='22023'; end if;

  perform 1
  from public.conversations c
  join public.conversation_members cm on cm.conversation_id=c.id
  where c.id=conversation_id_input and c.kind='direct' and cm.user_id=target_user_id_input;
  if not found then raise exception 'Conversation is not available for this safety review' using errcode='22023'; end if;

  insert into public.admin_dm_review_requests(admin_id,target_user_id,conversation_id,reason)
  values (auth.uid(),target_user_id_input,conversation_id_input,normalized_reason)
  returning id into request_id;

  insert into public.admin_dm_audit_log(request_id,admin_id,action,target_user_id,conversation_id,details)
  values (request_id,auth.uid(),'request',target_user_id_input,conversation_id_input,jsonb_build_object('reason',normalized_reason));
  return request_id;
end;
$$;

create or replace function public.admin_get_dm_review_messages(request_id_input uuid)
returns table (
  message_id uuid,sender_id uuid,sender_name text,sender_username text,body text,
  created_at timestamptz,edited_at timestamptz,deleted_at timestamptz,
  attachment_url text,reply_to_id uuid
)
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare review public.admin_dm_review_requests%rowtype;
begin
  perform 1 from auth.users u join public.profiles p on p.id=u.id
  where u.id=auth.uid()
    and lower(coalesce(u.email,''))='mreyadishere@gmail.com'
    and p.role='admin'
    and coalesce(p.account_status,'active')='active';
  if not found then raise exception 'Not authorized' using errcode='42501'; end if;

  select * into review
  from public.admin_dm_review_requests r
  where r.id=request_id_input and r.admin_id=auth.uid() and r.closed_at is null and r.expires_at>now();

  if not found or review.conversation_id is null then
    raise exception 'This safety review request is unavailable or expired' using errcode='42501';
  end if;

  insert into public.admin_dm_audit_log(request_id,admin_id,action,target_user_id,conversation_id,details)
  values (review.id,auth.uid(),'view',review.target_user_id,review.conversation_id,jsonb_build_object('expires_at',review.expires_at));

  return query
  select x.id,x.sender_id,p.full_name,p.username,
    case when x.deleted_at is null then x.body else null end,
    x.created_at,x.edited_at,x.deleted_at,
    case when x.deleted_at is null then x.attachment_url else null end,
    x.reply_to_id
  from (
    select m.* from public.messages m
    where m.conversation_id=review.conversation_id
    order by m.created_at desc
    limit 200
  ) x
  left join public.profiles p on p.id=x.sender_id
  order by x.created_at asc;
end;
$$;

revoke all on function public.admin_search_dm_users(text) from public, anon;
revoke all on function public.admin_list_user_dm_conversations(uuid) from public, anon;
revoke all on function public.admin_create_dm_review_request(uuid,uuid,text) from public, anon;
revoke all on function public.admin_get_dm_review_messages(uuid) from public, anon;

grant execute on function public.admin_search_dm_users(text) to authenticated;
grant execute on function public.admin_list_user_dm_conversations(uuid) to authenticated;
grant execute on function public.admin_create_dm_review_request(uuid,uuid,text) to authenticated;
grant execute on function public.admin_get_dm_review_messages(uuid) to authenticated;
