
create table if not exists public.message_reactions (
  id bigint generated by default as identity primary key,
  dm_message_id uuid references public.messages(id) on delete cascade,
  circle_message_id bigint references public.circle_messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  constraint message_reactions_one_target check (
    (dm_message_id is not null and circle_message_id is null)
    or
    (dm_message_id is null and circle_message_id is not null)
  ),
  constraint message_reactions_emoji_check check (char_length(emoji) between 1 and 16)
);

create unique index if not exists message_reactions_dm_unique
  on public.message_reactions(dm_message_id,user_id,emoji)
  where dm_message_id is not null;

create unique index if not exists message_reactions_circle_unique
  on public.message_reactions(circle_message_id,user_id,emoji)
  where circle_message_id is not null;

create index if not exists message_reactions_dm_idx on public.message_reactions(dm_message_id);
create index if not exists message_reactions_circle_idx on public.message_reactions(circle_message_id);
create index if not exists message_reactions_user_idx on public.message_reactions(user_id);

alter table public.message_reactions enable row level security;

drop policy if exists "participants read dm message reactions" on public.message_reactions;
create policy "participants read dm message reactions"
on public.message_reactions for select
to authenticated
using (
  dm_message_id is not null
  and exists (
    select 1
    from public.messages m
    join public.conversation_members cm on cm.conversation_id=m.conversation_id
    where m.id=message_reactions.dm_message_id
      and cm.user_id=auth.uid()
      and cm.hidden_at is null
  )
);

drop policy if exists "circle members read message reactions" on public.message_reactions;
create policy "circle members read message reactions"
on public.message_reactions for select
to authenticated
using (
  circle_message_id is not null
  and exists (
    select 1
    from public.circle_messages m
    join public.circle_members cm on cm.circle_id=m.circle_id
    where m.id=message_reactions.circle_message_id
      and cm.user_id=auth.uid()
      and cm.status in ('active','muted')
  )
);

drop policy if exists "participants react to dm messages" on public.message_reactions;
create policy "participants react to dm messages"
on public.message_reactions for insert
to authenticated
with check (
  user_id=auth.uid()
  and dm_message_id is not null
  and exists (
    select 1
    from public.messages m
    join public.conversation_members cm on cm.conversation_id=m.conversation_id
    where m.id=message_reactions.dm_message_id
      and cm.user_id=auth.uid()
      and cm.hidden_at is null
  )
);

drop policy if exists "circle members react to messages" on public.message_reactions;
create policy "circle members react to messages"
on public.message_reactions for insert
to authenticated
with check (
  user_id=auth.uid()
  and circle_message_id is not null
  and exists (
    select 1
    from public.circle_messages m
    join public.circle_members cm on cm.circle_id=m.circle_id
    where m.id=message_reactions.circle_message_id
      and cm.user_id=auth.uid()
      and cm.status='active'
  )
);

drop policy if exists "users remove own message reactions" on public.message_reactions;
create policy "users remove own message reactions"
on public.message_reactions for delete
to authenticated
using (user_id=auth.uid());

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='message_reactions'
  ) then
    alter publication supabase_realtime add table public.message_reactions;
  end if;
end $$;
